# Generated by Django 3.2.17 on 2023-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCarDetails',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
