# Generated by Django 3.2.17 on 2023-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230328_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('car', models.ManyToManyField(to='app.EmployeeCarDetails')),
            ],
        ),
    ]
